### ISSUE TITLE
Pc2Arduino communication protocol

### ISSUE THREAD

**Issue by meldew** [meldew/6_DOF_Robot_Control#1]
We need to create a protocol that communicates with Arduino via USB, and optionally via TCP/IP. Can start with the COM port. The following information should be sent and received through the protocol:

Sending: 6 Joint angles, start, stop, emergency stop.
Receiving: 6 Real-time joint angles calculated by the Arduino, 6 limit switches for each joint angle.

There should also be the possibility to easily add more variables that can be sent and received. The purpose of the program is as follows:

Regarding forward kinematics, we send the angles directly to the robot. For example, motor number 1 and 2 go to this angle. The angle and the following start commands should be sent to the Arduino, which then sends the command to the stepper motors.

Regarding inverse kinematics: We have inverse kinematics on the backend, which receives a position and orientation for the end effector from the user. For example, I tell the program that the robot should position the gripper at (x,y,z) = (5,5,5) and (r,p,y) = (0,0,0). The program receives the position of the end effector in Cartesian coordinate system and calculates the best angle for each joint. These joint angles should then be sent to the Arduino via the COM port.

**Comment by meldew** [comment]
pidor

**Comment by poorTiK** [comment]
Please clarify data types you expect, as I understand - 6 joint angles is **float** in range **0-360**, but what is start, stop, and emergency stop?

**Comment by meldew** [comment]
yes, 6 joint agnles are floats 0-360 degrese, where start, stop, emergency, and limit switches is a bool variable type

**Comment by meldew** [comment]
![Image](https://github.com/meldew/6_DOF_Robot_Control/assets/47281451/fd3aa4a2-3391-4602-ad30-509726f39f24)

why are u ge

**Comment by meldew** [comment]
done
